### PR TITLE
Reduced cache time

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Review by aahnik — COMMENTED** [review]
could you please link the relevant docs for the cache time variable in ptb.

I think the problem, can be solved by making unique id.

Earlier my ids were by chance becoming same, the caching works based in id of the result.

I am planning to use uuid4 to generate unique ids

**Comment by SmartManoj** [comment]
[Docs](https://core.telegram.org/bots/api#answerinlinequery:~:text=query-,cache_time)

**Comment by aahnik** [comment]
please see my latest commit 4958e2458ea49b782bdc65b2e2d5af0b12a597dd

**Comment by aahnik** [comment]
> [Docs](https://core.telegram.org/bots/api#answerinlinequery:~:text=query-,cache_time)
image

**Review by aahnik — APPROVED** [review]
tested, and no errors are coming. Thanks a lot for the contrib. I am not sure whether this will solve the problem of incorrect result cached. For 30s it will be incorrect, after that it will be re-evaluated. I have made the id more unique. 

this is such a problem that it is not reproducible easily. We have to kinda hit and trial

**Comment by aahnik** [comment]
@all-contributors please add @SmartManoj  for bug

**Pull request merged**
